# Generated by Django 4.2.30 on 2026-05-14 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('age', models.PositiveIntegerField()),
                ('date_of_birth', models.DateField()),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('vehicle_number', models.CharField(max_length=20)),
                ('license_number', models.CharField(max_length=30, unique=True)),
                ('vehicle_brand', models.CharField(choices=[('toyota', 'Toyota'), ('nissan', 'Nissan'), ('tata', 'Tata'), ('hyundai', 'Hyundai'), ('bmw', 'BMW'), ('mercedes', 'Mercedes-Benz'), ('audi', 'Audi'), ('honda', 'Honda'), ('ford', 'Ford'), ('volkswagen', 'Volkswagen'), ('kia', 'Kia'), ('mahindra', 'Mahindra'), ('suzuki', 'Suzuki'), ('tesla', 'Tesla'), ('rivian', 'Rivian'), ('other', 'Other')], max_length=20)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='drivers/')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=15)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('total_alerts', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver Profile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('interrupted', 'Interrupted')], default='active', max_length=15)),
                ('total_alerts', models.PositiveIntegerField(default=0)),
                ('total_fatigue_events', models.PositiveIntegerField(default=0)),
                ('eye_closure_count', models.PositiveIntegerField(default=0)),
                ('max_closure_duration', models.FloatField(default=0.0)),
                ('route_start_lat', models.FloatField(blank=True, null=True)),
                ('route_start_lng', models.FloatField(blank=True, null=True)),
                ('last_known_lat', models.FloatField(blank=True, null=True)),
                ('last_known_lng', models.FloatField(blank=True, null=True)),
                ('safety_score', models.FloatField(default=100.0)),
                ('notes', models.TextField(blank=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.driverprofile')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='CompanyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_registration', 'New Driver Registration'), ('fatigue_alert', 'Fatigue Alert'), ('accident_alert', 'Accident Alert'), ('session_complete', 'Session Completed'), ('system', 'System Notification')], max_length=25)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.driverprofile')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.monitoringsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('drowsiness', 'Drowsiness Detected'), ('eye_closure', 'Prolonged Eye Closure'), ('fatigue', 'Fatigue Warning'), ('distraction', 'Driver Distraction'), ('accident', 'Accident Detected'), ('emergency', 'Emergency Alert'), ('yawning', 'Yawning Detected')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('ear_value', models.FloatField(blank=True, null=True)),
                ('snapshot_path', models.CharField(blank=True, max_length=255)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_alerts', to='core.driverprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.monitoringsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AccidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('false_alarm', 'False Alarm')], default='reported', max_length=15)),
                ('description', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('emergency_contacted', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to='core.driverprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to='core.monitoringsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
