# Generated by Django 4.2.30 on 2026-05-15 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_driverlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlocation',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='driverlocation',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.driverprofile'),
        ),
        migrations.AlterField(
            model_name='driverlocation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
